In [111]:
import numpy as np
#question 1
A = np.array([
    [1, -2, 3, 1],
    [2, 5, -1, 3],
    [4, 1, 0, 2],
    [0, -2, 3, 1]
])
print(A)

[[ 1 -2  3  1]
 [ 2  5 -1  3]
 [ 4  1  0  2]
 [ 0 -2  3  1]]


In [112]:
#question 2
colonne_3 = A[:, 2]
print(colonne_3)
ligne_4 = A[3, :]
print(ligne_4)

[ 3 -1  0  3]
[ 0 -2  3  1]


In [113]:
#question 3
A[:, 2] = np.array([1, 1, 1, 1])
print(A)

[[ 1 -2  1  1]
 [ 2  5  1  3]
 [ 4  1  1  2]
 [ 0 -2  1  1]]


In [114]:
#question 4
det_A = np.linalg.det(A)
trace_A = np.trace(A)

print("Déterminant de A :", det_A)
print("Trace de A :", trace_A)

Déterminant de A : -0.9999999999999938
Trace de A : 8


In [115]:
#question 5
b = np.array([1, 2, -1, 3])

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, b)

print("Solution du système x :")
print(x)

print("Inverse de A :")
print(A_inv)


Solution du système x :
[ -2.  -5. -26.  19.]
Inverse de A :
[[ 1.00000000e+00  9.43689571e-16 -1.99840144e-15 -1.00000000e+00]
 [ 6.00000000e+00  1.00000000e+00 -2.00000000e+00 -5.00000000e+00]
 [ 3.40000000e+01  5.00000000e+00 -1.10000000e+01 -2.70000000e+01]
 [-2.20000000e+01 -3.00000000e+00  7.00000000e+00  1.80000000e+01]]


In [116]:
#question 6
B = A[:,1:3]
C = A[:2, :]
D = A[1:, 1:]

print("Matrice B :")
print(B)

print("Matrice C :")
print(C)

print("Matrice D :")
print(D)

M = np.dot(C, C.T)

print("Matrice M :")
print(M)


Matrice B :
[[-2  1]
 [ 5  1]
 [ 1  1]
 [-2  1]]
Matrice C :
[[ 1 -2  1  1]
 [ 2  5  1  3]]
Matrice D :
[[ 5  1  3]
 [ 1  1  2]
 [-2  1  1]]
Matrice M :
[[ 7 -4]
 [-4 39]]


M est une matrice symétrique positive (mais pas nécessairement définie, on dit alors qu'elle est semi-définie je crois).

In [117]:
valeurs_propres, vecteurs_propres = np.linalg.eigh(M)
P = vecteurs_propres
D = np.diag(valeurs_propres)
P_transpose = P.T
verification = np.dot(P,P_transpose)#== np.eye(2)

print("Matrice D (diagonale) :")
print(D)

print("Matrice de passage P :")
print(P)

print(f"La matrice de passage P est orthogonale ? {verification}")


Matrice D (diagonale) :
[[ 6.5075775  0.       ]
 [ 0.        39.4924225]]
Matrice de passage P :
[[-0.99250756 -0.12218326]
 [-0.12218326  0.99250756]]
La matrice de passage P est orthogonale ? [[1. 0.]
 [0. 1.]]


Le théorème mis en évidence ici est le théorème spectral.