In [333]:
import numpy as np
import numpy.linalg as alg

# Vecteurs

In [1]:
# vecteur colonne
x=np.array([[1],[-3],[4]])     # doubles crochets
print('x=')
print(x)
print('dim(x)=',x.shape,'\n')

# vecteur ligne
y=np.array([[3,2,-3,7]])       # doubles crochets
print('y=')
print(y)
print('dim(y)=',y.shape,'\n')

# transposition
print('transposée de x :')  
print(x.T,'\n')                # vecteur ligne
print('transposée de y :')  
print(y.T,'\n')                # vecteur colonne

# vecteurs particuliers
u=np.ones((4,1))               # doubles parenthèses
print('u=')
print(u)
v=np.zeros((1,6))              # doubles parenthèses
print('v=')
print(v,'\n')


NameError: name 'np' is not defined

# Produit de vecteurs

In [335]:
# produit scalaire = (vecteur ligne) @ (vecteur colonne) où @ est le produit matriciel
# (les vecteurs doivent avoir le même nombre de composantes)
x=np.array([[1],[-3],[4]])       # vecteur colonne
y=np.array([[-2],[1],[-5]])      # vecteur colonne
print('produit scalaire : ', x.T@y,'\n')        
print('produit scalaire : ', y.T@x,'\n')

# produit (vecteur colonne) @ (vecteur ligne) où @ est le produit matriciel
# (le nombre de composantes des vecteurs peut être différent)
x=np.array([[-2],[1],[-3],[4]])  # vecteur colonne
y=np.array([[-2],[1],[-5]])      # vecteur colonne
print('produit vecteur colonne x par vecteur ligne y : ')
print(x@y.T,'\n')

print('produit vecteur colonne y par vecteur ligne x : ')
print(y@x.T,'\n')                # on obtient la transposée de x@y.T (en effet : y@x.T=(x@y.T).T)

produit scalaire :  [[-25]] 

produit scalaire :  [[-25]] 

produit vecteur colonne x par vecteur ligne y : 
[[  4  -2  10]
 [ -2   1  -5]
 [  6  -3  15]
 [ -8   4 -20]] 

produit vecteur colonne y par vecteur ligne x : 
[[  4  -2   6  -8]
 [ -2   1  -3   4]
 [ 10  -5  15 -20]] 



# Création d'une matrice

In [336]:
A=np.array( [ [1, -2, 3], [-3, 4, 1], [1, 2, 1] ])
print('A=')
print(A)
print('dimension de A :', A.shape)  # alternative : np.shape(A)

# transposition
print('transposée de A : ')
print(A.T)                          # alternative : np.transpose(A)

# type des éléments d'une matrice
print('type des éléments de A :',A.dtype,'\n') # type entier

B=np.array([ [-1.0,2.2,6.5], [3.0,-5.4,2.3], [1.7, 3.7, -1.0]])
print('type des éléments de B :', B.dtype) # type flottant
   
C=np.array([[1,2],[3,4]],dtype=float)
print('C=')
print(C)
print('type des éléments de C :', C.dtype, '\n')  # type flottant

A=
[[ 1 -2  3]
 [-3  4  1]
 [ 1  2  1]]
dimension de A : (3, 3)
transposée de A : 
[[ 1 -3  1]
 [-2  4  2]
 [ 3  1  1]]
type des éléments de A : int64 

type des éléments de B : float64
C=
[[1. 2.]
 [3. 4.]]
type des éléments de C : float64 



# Accès aux éléments d'une matrice

In [337]:
print('1ère ligne, 3ème colone : ', A[0,2],'\n')  

print('2ème colonne (sous forme de tableau) : ', A[:,1],'\n')   
print('2ème colonne (sous forme de vecteur colonne) : \n') 
print(A[:,1:2],'\n') 

print('3ème ligne (sous forme de tableau) : ', A[2,:],'\n')   
print('3ème ligne (sous forme de vecteur ligne) : ', A[2:3,:],'\n')

A1=A[1:3,0:2]        # sous-matrice de A (lignes 2 et 3, colonnes 1 et 2)
print('sous-matrice de A (lignes 2 et 3, colonnes 1 et 2) : \n')
print(A1,'\n')

1ère ligne, 3ème colone :  3 

2ème colonne (sous forme de tableau) :  [-2  4  2] 

2ème colonne (sous forme de vecteur colonne) : 

[[-2]
 [ 4]
 [ 2]] 

3ème ligne (sous forme de tableau) :  [1 2 1] 

3ème ligne (sous forme de vecteur ligne) :  [[1 2 1]] 

sous-matrice de A (lignes 2 et 3, colonnes 1 et 2) : 

[[-3  4]
 [ 1  2]] 



# Matrices particulières

In [338]:
print('matrice de dimension 2x4 dont les éléments sont tous nuls : \n')
M=np.zeros((2,4))
print(M,'\n')

print('matrice de dimension 3x2 dont les éléments valent tous 1 : \n')
N=np.ones((3,2)) 
print(N,'\n')

print('matrice identité : \n')
I=np.eye(4)       
print(I,'\n')

print('matrice diagonale : \n')
D=np.diag([-3,2,6,-7]) 
print(D,'\n')

print('matrice 3x5 de nombres aléatoires entre 0 et 1 : \n')
R=np.random.rand(3,5)
print(R,'\n')

matrice de dimension 2x4 dont les éléments sont tous nuls : 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

matrice de dimension 3x2 dont les éléments valent tous 1 : 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

matrice identité : 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

matrice diagonale : 

[[-3  0  0  0]
 [ 0  2  0  0]
 [ 0  0  6  0]
 [ 0  0  0 -7]] 

matrice 3x5 de nombres aléatoires entre 0 et 1 : 

[[0.83029806 0.28378719 0.55830087 0.64341379 0.76171624]
 [0.31603658 0.06023992 0.55025131 0.16147188 0.68564782]
 [0.71329551 0.61578556 0.06651248 0.56896427 0.29324829]] 



# Opérations terme à terme

In [339]:
B=np.array([ [-1,2,6], [3,-5,2], [1,3,-1]])

print('addition terme à terme : A+B=\n')
print(A+B,'\n')    

print('soustraction terme à terme : A-B=\n')
print(A-B,'\n')   

print('multiplication terme à terme : A*B=\n')
print(A*B,'\n')    

print('division terme à terme : A/B=\n')
print(A/B,'\n')    

addition terme à terme : A+B=

[[ 0  0  9]
 [ 0 -1  3]
 [ 2  5  0]] 

soustraction terme à terme : A-B=

[[ 2 -4 -3]
 [-6  9 -1]
 [ 0 -1  2]] 

multiplication terme à terme : A*B=

[[ -1  -4  18]
 [ -9 -20   2]
 [  1   6  -1]] 

division terme à terme : A/B=

[[-1.         -1.          0.5       ]
 [-1.         -0.8         0.5       ]
 [ 1.          0.66666667 -1.        ]] 



# Concaténation de matrices

In [340]:
print(np.concatenate((A,B),axis=0),'\n')   # concaténation des matrices A et B sur 
                                           # l'axe vertical (l'une sur l'autre)
print(np.concatenate((A,B),axis=1),'\n')   # concaténation des matrices A et B sur 
                                           # l'axe horizontal (côte à côte)

# alternatives
print(np.vstack((A,B)),'\n')   # concaténation verticale
print(np.hstack((A,B)),'\n')   # concaténation horizontale


[[ 1 -2  3]
 [-3  4  1]
 [ 1  2  1]
 [-1  2  6]
 [ 3 -5  2]
 [ 1  3 -1]] 

[[ 1 -2  3 -1  2  6]
 [-3  4  1  3 -5  2]
 [ 1  2  1  1  3 -1]] 

[[ 1 -2  3]
 [-3  4  1]
 [ 1  2  1]
 [-1  2  6]
 [ 3 -5  2]
 [ 1  3 -1]] 

[[ 1 -2  3 -1  2  6]
 [-3  4  1  3 -5  2]
 [ 1  2  1  1  3 -1]] 



# Maximum, minimum, moyenne d'une matrice

In [341]:
print(np.amax(A),'\n')
print(np.amin(A),'\n')
print(np.mean(A),'\n')

4 

-3 

0.8888888888888888 



# Calcul matriciel 

In [342]:
# produit matriciel
print('AB=')
print(A@B,'\n')
print('BA=')
print(B@A,'\n')

# trace et déterminant d'une matrice
print('trace de A : ', np.trace(A))
print('déterminant de A : ', alg.det(A))

# rang d'une matrice
print('rang de A : ', alg.matrix_rank(A),'\n')

# inversion
print('inverse de A : ')
print(alg.inv(A),'\n')

# résolution d'un système linéaire Ax=b
b=np.array([[2],[1],[-3]])                 # vecteur colonne
x=alg.inv(A)@b                             # alternative : x=alg.solve(A,b)
print('solution de Ax=b : x = ')   
print(x,'\n')              


AB=
[[ -4  21  -1]
 [ 16 -23 -11]
 [  6  -5   9]] 

BA=
[[ -1  22   5]
 [ 20 -22   6]
 [ -9   8   5]] 

trace de A :  6
déterminant de A :  -36.0
rang de A :  3 

inverse de A : 
[[-0.05555556 -0.22222222  0.38888889]
 [-0.11111111  0.05555556  0.27777778]
 [ 0.27777778  0.11111111  0.05555556]] 

solution de Ax=b : x = 
[[-1.5]
 [-1. ]
 [ 0.5]] 



# Diagonalisation

In [345]:
print('coefficients du polynome caractéristique de A par degré décroissant : ', np.poly(A),'\n')      

print('liste des valeurs propres de A : ', alg.eigvals(A),'\n')  

# calcul des valeurs propres (eigenvalues) et des vecteurs propres (P : matrice de passage) 
eigenvalues,P=alg.eig(A)
print('liste des valeurs propres de A : ', eigenvalues,'\n')    
print('vecteurs porpres de A (matrice de passage) : P = \n')
print(P,'\n')               

# matrice diagonale
D=np.diag(eigenvalues)      # matrice diagonale
print('matrice diagonale : D = \n')
print(D,'\n')

# calcul de P.D.inv(P)
print('P.D.inv(P) = \n')
print(P@D@alg.inv(P),'\n')  # on retrouve A

coefficients du polynome caractéristique de A par degré décroissant :  [ 1. -6. -2. 36.] 

liste des valeurs propres de A :  [-2.2181867  4.9185226  3.2996641] 

liste des valeurs propres de A :  [-2.2181867  4.9185226  3.2996641] 

vecteurs porpres de A (matrice de passage) : P = 

[[-0.74327228 -0.13324263  0.37494279]
 [-0.43968206  0.89610674  0.61259155]
 [ 0.50420829  0.42336641  0.69580852]] 

matrice diagonale : D = 

[[-2.2181867  0.         0.       ]
 [ 0.         4.9185226  0.       ]
 [ 0.         0.         3.2996641]] 

P.D.inv(P) = 

[[ 1. -2.  3.]
 [-3.  4.  1.]
 [ 1.  2.  1.]] 

